version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
      DANGER_CIRCLE_CI_API_TOKEN: 31b9afde32782399cb1f7df87d8e73755391e0c3
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: create dummy file
          command: echo > signconfig.gradle
      - run:
          name: Download Android Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - restore_cache:
          key: v1-bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Download Ruby Dependencies
          command: bundle install --path=vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-bundle-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run Test
          command: ./gradlew testDebug
      - run:
          name: Run Lint
          command: ./gradlew lintDebug
      - run:
          name: Run Danger
          command: bundle exec danger
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - run:
          name: Build debug APK
          command: ./gradlew assembledebug
      - run:
          name: save deploygate
          command: COMMIT_MESSAGE=`git log --oneline -n 1 $CIRCLE_SHA1` && curl -F "file=@app/build/outputs/apk/debug/app-debug.apk" -F "token=9e537788a7539758d6b9c7d54ee15ab6c6e8b206" -F "message=${COMMIT_MESSAGE}" https://deploygate.com/api/users/koba_mako/apps
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk

